### PR TITLE
Bump build number to rerender the devel branch

### PR DESCRIPTION
**Pull request by seisman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by seisman** [comment]
@conda-forge-admin, please rerender

**Comment by seisman** [comment]
@weiji14 It seems that the devel branch is not rendered for a long time. That's one of the main reasons that the master and devel branches diff a lot. I'm wondering if the bot can render the automatic PRs (e.g., https://github.com/conda-forge/gmt-feedstock/pull/110) from the GenericMappingTools organization.

This PR bumps the build number to rerender the devel branch.

**Review by weiji14 — COMMENTED** [review]
> I'm wondering if the bot can render the automatic PRs (e.g., #110) from the GenericMappingTools organization.

That's a good question, I'll trigger a new automatic PR and see if re-rendering can work (i.e. it should look like this PR).

**Comment by seisman** [comment]
> I'll trigger a new automatic PR and see if re-rendering can work (i.e. it should look like this PR).

OK. I'll keep this PR open, and see it your automatic PR can be re-rendered.

**Comment by weiji14** [comment]
> > I'll trigger a new automatic PR and see if re-rendering can work (i.e. it should look like this PR).
> 
> OK. I'll keep this PR open, and see it your automatic PR can be re-rendered.

Right, so re-rendering doesn't work on `GenericMappingTools/gmt-feedstock` (see https://github.com/conda-forge/gmt-feedstock/pull/122#issuecomment-728481865). Let's merge this PR then.

**Comment by seisman** [comment]
> Right, so re-rendering doesn't work on GenericMappingTools/gmt-feedstock (see #122 (comment)). Let's merge this PR then.

Perhaps we can run `conda smithy rerender -c auto` in your workflow to manually re-render the feedstock.

**Comment by weiji14** [comment]
> Perhaps we can run `conda smithy rerender -c auto` in your workflow to manually re-render the feedstock.

Good idea, but I still need to figure out the authentication stuff as well to make it fully automated :sweat_smile:

**Pull request merged**
