### PR TITLE
Update GMT source to GitHub repo

### PR DESCRIPTION
**Pull request by seisman**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

@conda-forge-admin, please rerender.

### CODE REVIEW

**Comment by seisman** [comment]
@conda-forge-admin, please rerender.

**Comment by seisman** [comment]
Have no idea why circleci build fails:
```
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['/opt/conda/bin/git', 'clone', '--mirror', 'https://github.com/GenericMappingTools/gmt.git', '/home/conda/feedstock_root/build_artifacts/git_cache/github.com/GenericMappingTools/gmt.git']' returned non-zero exit status 127.
Failed to download or patch source. Please see build log for info.
Exited with code 1
```

**Comment by leouieda** [comment]
@conda-forge-admin, please rerender

**Comment by leouieda** [comment]
@seisman I'm still scratching my head over this one. I'll try to rebuild to see if this was fixed upstream somehow.

**Comment by leouieda** [comment]
We're now failing because of incompatibility between gdal and hdf5 versions that conda-forge has pinned. See conda-forge/gdal-feedstock#239. Maybe after conda-forge/gdal-feedstock#237 is merged we can get this to work.

**Comment by seisman** [comment]
@leouieda The gdal issue seems fixed. Can you try to rebuild this PR?

**Comment by leouieda** [comment]
Seems like the builds are all passing now. Will merge this in and we can update later after #57 is merged.

**Pull request merged**
