### PR TITLE
Update to 6.0.0a9 (trunk r19245)

### PR DESCRIPTION
**Pull request by leouieda**
This update includes the refactoring of the GMT_Dataset that Paul did.

### CODE REVIEW

**Comment by leouieda** [comment]
@joa-quim I'll merge this once the CI builds pass and the packages will be built and uploaded automatically after that. The OSX build on Travis CI can take quite a while to run and it will have to run at least twice.

**Comment by joa-quim** [comment]
@leouieda I'm afraid you'll have to rebuild this again. There were more changes to the GMT_MATRIX, VECTOR ... containers that will probably break the Julia wrapper.

And, I tried to use this new build today but it still errored because it couldn't find recently added functions (GMT_Set_AllocMode)

**Comment by joa-quim** [comment]
@leouieda I'm afraid you'll have to rebuild this again. There were more changes to the GMT_MATRIX, VECTOR ... containers that will probably break the Julia wrapper.

And, I tried to use this new build today but it still errored because it couldn't find recently added functions (GMT_Set_AllocMode)

**Comment by leouieda** [comment]
@joa-quim I'm updating it to r19245 from trunk. It will take some time and the built package will only be available after this PR is merged and the CIs run again. So your builds will still fail for a while.

**Pull request merged**
