### PR TITLE
Update to 6.0.0 in master branch

### PR DESCRIPTION
**Pull request by seisman**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by seisman** [comment]
@conda-forge-admin, please rerender

**Comment by seisman** [comment]
Currently, this PR tries to build GMT 6.0.0rc4 on master branch to make sure it works. After 6.0.0 is released, I'll update it to 6.0.0.

**Comment by seisman** [comment]
@conda-forge-admin, please rerender

**Comment by leouieda** [comment]
@seisman the README is created automatically from the `meta.yml` on rerender. That might be what is tripping up the bot.

**Comment by leouieda** [comment]
Could you try reverting that and rerendering locally?

**Comment by seisman** [comment]
The README file was modified by previous rerendering. Anyway, I've rerendered it locally and pushed the changes.

**Comment by seisman** [comment]
@leouieda The builds pass. Please review it.

**Pull request merged**
