### PR TITLE
 Upgrade to the new Jinja2 compiler syntax 

### PR DESCRIPTION
**Pull request by leouieda**
This time I ran `conda smithy update-cb3`.

@ocefpaf how does that look?

### CODE REVIEW

**Comment by leouieda** [comment]
@ocefpaf I've been scratching my head here about this segfault that is happening on linux but not mac. Any ideas? Could it be the change in compilers? It wasn't segfaulting before.

**Comment by ocefpaf** [comment]
> Could it be the change in compilers?

We did not change the compilers yet, just using the old toolchain to activate the flags, etc.
Maybe some of the flags are interfering with the build here or the new pinnings are the culprit.

@isuruf do you have an idea where to start investigating?

**Comment by leouieda** [comment]
Thanks, Filipe. It doesn't help that the cmake build is very stubborn and refuses to work on my machine with the conda env netcdf.

**Comment by ocefpaf** [comment]
> Thanks, Filipe. It doesn't help that the cmake build is very stubborn and refuses to work on my machine with the conda env netcdf.

Are you using the docker image to build packages locally?

**Comment by leouieda** [comment]
> Are you using the docker image to build packages locally?

No. Are there instructions for doing that?

**Comment by isuruf** [comment]
https://conda-forge.org/docs/testing.html#run-docker-tests-locally-for-feedstock

**Pull request merged**
