### PR TITLE
Enable OSX build

### PR DESCRIPTION
**Pull request by leouieda**

### CODE REVIEW

**Comment by leouieda** [comment]
@ocefpaf getting a weird error that conda build can't find the libgmt file:

    Fixing linking of /Users/travis/miniconda3/conda-bld/gmt_1494532316952/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place//Users/travis/miniconda3/conda-bld/gmt_1494532316952/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libgmt.5.dylib in /Users/travis/miniconda3/conda-bld/gmt_1494532316952/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libgmt.5.4.1.dylib

    Error: Could not find /Users/travis/miniconda3/conda-bld/gmt_1494532316952/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libgmt.5.dylib

I've also noted that cmake is linking against the system `libcurl` instead of the conda one. Would this be a problem when installing without a system curl?

**Comment by ocefpaf** [comment]
> @ocefpaf getting a weird error that conda build can't find the libgmt file:

Macs :weary: 

Maybe we need to use `install_name_tool -change`. Not sure. @msarahan if you have some free time can you take a quick look?

> I've also noted that cmake is linking against the system `libcurl` instead of the conda one.

I've seen that problem before in `conda-forge`. I'll poke around to see if I can find a solution.

> Would this be a problem when installing without a system curl?

It can be in some cases.

**Comment by ocefpaf** [comment]
:tada:

**Comment by ocefpaf** [comment]
The mapping/GIS folks from my office want to send a special thanks to @mingwandroid for helping us solve the mystery with the GMT builds. This is an example of how SciPy live interactions can help us move things forward!

**Comment by leouieda** [comment]
I second that. This would not with been possible without Ray.

**Comment by mingwandroid** [comment]
Thanks guys. It was a pleasure, and really nice to meet you both. Shame the fix is a bit hacky but at least people on macOS can use the software now.

**Comment by leouieda** [comment]
We'll get it sorted out eventually :)

**Pull request merged**
