### PR TITLE
Do not link to mkl

### LINKED ISSUE #2: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory
I just did `conda install gmt` into a Python 3 environment on an `openSUSE Leap 42.1 (x86_64)` system:
```
(IOOS3) rsignell@gamone:~> conda list gmt
# packages in environment at /home/rsignell/miniconda3/envs/IOOS3:
#
gmt                       5.3.3                         0    conda-forge
```

When when I try to run a GMT command, I get: 
```
(IOOS3) rsignell@gamone:~> xyz2grd --help
xyz2grd: error while loading shared libraries: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory
```

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #2 

Ping @rsignell-usgs

### CODE REVIEW

**Comment by leouieda** [comment]
@ocefpaf is there a reason that `blas` was added as a runtime dependency? GMT doesn't really use and from I understand it's only there to make sure GMT isn't tied to MKL.

This is causing some problems for people on OSX with the Accelerate framework. LAPACK is getting conflicts with the conda-forge openblas.

**Comment by ocefpaf** [comment]
I don't recall the details but the issue was to force the `gsl` that was linked with `openblas`.
A lot has changed since then and we should revisit this.

Ping @isuruf who is probably more on top of these than myself. (It is hurricane season and the day job has been quite demanding theses past weeks.)

**Comment by isuruf** [comment]
GMT is using LAPACK right?

**Comment by leouieda** [comment]
@ocefpaf thanks for the update! I'm sure you're really busy doing awesome work. Good luck!

> GMT is using LAPACK right?

@isuruf it is. This is what is causing problems. On OSX, it's looking at the Accelerate install which complains about openblas.

This is the error that user @egayer got:

    dlopen(libgmt.dylib, 6): Library not loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

    Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    Reason: Incompatible library version: vecLib requires version 1.0.0 or later, but libopenblas.dylib provides version 0.0.0

**Comment by isuruf** [comment]
@leouieda, that should be easy to fix. Add `-DLAPACK_LIBRARIES=$PREFIX/lib/liblapack${SHLIB_EXT}` to the cmake command line.

**Comment by leouieda** [comment]
@isuruf thanks! I'll try it out.

**Comment by leouieda** [comment]
But why is "blas" a runtime dependency if GMT is not using it?

Currently, installing GMT forces the install of numpy with blas instead of mkl. 
Is there any way around it?

**Pull request merged**
