### PR TITLE
Update dev release to 6.0.0rc3

### PR DESCRIPTION
**Pull request by seisman**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by seisman** [comment]
@leouieda We're having trouble with the FFTW package again.

**Comment by leouieda** [comment]
😑 that is lovely...

Thanks for opening the PR. I'll Google around and see if anyone else is having this issue again.

**Comment by seisman** [comment]
I did nothing but we have a different error now:
```
Unsatisfiable dependencies for platform win-64: {"python[version='>=3.7,<3.8.0a0']"}
```

Do you think we can drop Windows package temporarily and build 6.0.0rc3 packages for Linux and macOS only.

**Comment by weiji14** [comment]
Exact conflict is this I think:
```
- gdal=2.4 -> python[version='>=3.7,<3.8.0a0']
```
I can't see why it is trying to use python 3.7 though since there's a conda-forge `gdal==2.4.1` package for python 3.6.

**Comment by seisman** [comment]
When build packages, It seems conda uses Python 3.7 on Linux and macOS, and uses Python 3.6 on Windows.

Windows build:
```
pyrsistent                0.15.3           py36hfa6e2cd_0    conda-forge
pysocks                   1.6.8                    py36_0    defaults
python                    3.6.5                h0c2934d_0    defaults
python-dateutil           2.8.0                      py_0    conda-forge
python-libarchive-c       2.8                     py36_10    defaults
pytz                      2019.1                     py_0    conda-forge
pywin32                   223              py36hfa6e2cd_1    defaults
pyyaml                    5.1.1            py36hfa6e2cd_0    conda-forge
```

Linux build:
```
pysocks                   1.7.0                    py37_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-libarchive-c       2.8                   py37_1004    conda-forge
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1.1            py37h516909a_0    conda-forge
```

**Comment by weiji14** [comment]
So the previous successful windows [build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=47074) used

```
win-64/gdal-2.4.1-py37he6b6c38_5.tar.bz2
# depends on
libgdal 2.4.1 h6b3497b_5, numpy >=1.14.6,<2.0a0, python >=3.7,<3.8.0a0, vc >=14.1,<15.0a0
```
whereas the failed build now is trying to get:
```
win-64/gdal-2.4.1-py37he6b6c38_6.tar.bz2
# depends on
libgdal 2.4.1 h32c7a2a_6, numpy >=1.14.6,<2.0a0, python >=3.7,<3.8.0a0, vc >=14.1,<15.0a0
```

**Comment by weiji14** [comment]
@seisman, try pinning vc to '14.1' instead of '14' in the .ci_support/win_c_compilervs2015vc14.yaml file.

**Comment by seisman** [comment]
files like `.ci_support/win_c_compilervs2015vc14.yaml` are automatically updated by conda robot. Not sure if I can change it.

**Comment by leouieda** [comment]
@weiji14 thanks for the detective work. It seems that this is caused by the latest build of gdal. Maybe @ocefpaf has some insights.

**Comment by leouieda** [comment]
If we need the Mac and Linux packages urgently, we should disable Windows for now. This is an RC anyway.

**Comment by seisman** [comment]
@conda-forge-admin, please rerender

**Comment by seisman** [comment]
@leouieda I think it's OK to merge.

**Comment by leouieda** [comment]
:+1: looks good to me

**Comment by leouieda** [comment]
:+1: looks good to me

**Comment by ocefpaf** [comment]
> @weiji14 thanks for the detective work. It seems that this is caused by the latest build of gdal. Maybe @ocefpaf has some insights.

Sorry. Still catching up with my messages after scipy. Indeed we have a problem with `gdal` due to an ABI breakage on `cfitsio` and now a conda-build bug, but I'm slowly fixing them and your mileage may vary (works on some combinations of dependencies and other don't work yet.)

**Pull request merged**
