### PR TITLE
Update dev release to 6.0.0rc1 

### PR DESCRIPTION
**Pull request by leouieda**
Trying out a build of the 6.0 release candidate. Once tarballs are published, will update to use them instead of Github.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leouieda** [comment]
For some reason, the path to the GMT SHAREDIR started getting hard-coded in this branch. From the Azure log:

```
gmt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir D:/bld/gmt_1560896377606/_h_env/Library/share/gmt/postscriptlight
```

whereas on master we get:
 
```
gmt: GMT: 4. gmt_getsharepath trying SHAREDIR subdir D:/bld/gmt_1559986067825/_test_env/Library/share/gmt/postscriptlight
```

I don't know why this started happening on Windows since it doesn't impact linux/osx.

@seisman, any insights?

**Comment by seisman** [comment]
I think this is also related to https://github.com/GenericMappingTools/gmt/issues/962#issuecomment-503333867, https://github.com/GenericMappingTools/gmt/issues/962#issuecomment-503334387.

Actually now i'm confused why the mac/linux build works.

**Comment by leouieda** [comment]
I'm guessing this is the reason why it works on mac and linux: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=43080&view=logs&jobId=ce7cbaa7-582c-5570-40f4-267b3d85fc9f&taskId=4a56039b-7269-50ae-de7a-538e91e6de06&lineStart=1377&lineEnd=1378&colStart=1&colEnd=1

Seems like the hardcoded link is being changed.

**Comment by seisman** [comment]
> I'm guessing this is the reason why it works on mac and linux: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=43080&view=logs&jobId=ce7cbaa7-582c-5570-40f4-267b3d85fc9f&taskId=4a56039b-7269-50ae-de7a-538e91e6de06&lineStart=1377&lineEnd=1378&colStart=1&colEnd=1
> 
> Seems like the hardcoded link is being changed.

I can see many messages like:
```
Detected hard-coded path in text file bin/gmt-config
Detected hard-coded path in text file include/gmt/config.h
Detected hard-coded path in binary file bin/gmt
Detected hard-coded path in binary file lib/gmt/plugins/supplements.so
Detected hard-coded path in binary file lib/libgmt.6.0.0.dylib
Detected hard-coded path in binary file lib/libgmt.6.dylib
Detected hard-coded path in binary file lib/libgmt.dylib
Detected hard-coded path in binary file lib/libpostscriptlight.6.0.0.dylib
Detected hard-coded path in binary file lib/libpostscriptlight.6.dylib
Detected hard-coded path in binary file lib/libpostscriptlight.dylib
```

**Comment by seisman** [comment]
hard-coded paths are detected, but I don't see where the paths are changed.

**Comment by seisman** [comment]
@leouieda Please update the PR. Maybe we can use the tarballs from github releases (https://github.com/GenericMappingTools/gmt/releases/tag/6.0.0rc1).

**Comment by seisman** [comment]
@leouieda I remember we have to set COPY_GSHHG and COPY_DCW to true on Windows. Maybe you can check if it's still necessary.

**Comment by leouieda** [comment]
@seisman good point :+1:

**Comment by leouieda** [comment]
It's still needed. The data path is still being hard coded.

**Comment by leouieda** [comment]
@seisman all tests pass now. Can you think anything else that needs to be done before merging?

**Comment by seisman** [comment]
I think it's good to merge.

**Comment by leouieda** [comment]
@seisman I'm trying to install the package on my machine in a blank environment and keep getting 

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - gmt=6.0.0rc1
```

Same happens with 6.0.0a19 but not with 5.4.5. Could you please try it out and see if you get the same error?

**Comment by seisman** [comment]
I don't see any problem. This is what I did:
```
$ conda create --name myenv-test python=3.7
$ conda activate myenv-test
$ which python
/Users/seisman/.anaconda/envs/myenv-test/bin/python
$ conda install -c conda-forge/label/dev gmt
... install many packages ... 

$ which gmt
/Users/seisman/.anaconda/envs/myenv-test/bin/gmt

$ gmt --version
6.0.0rc1

$ conda list
# packages in environment at /Users/seisman/.anaconda/envs/myenv-test:
#
# Name                    Version                   Build  Channel
boost-cpp                 1.70.0               hd59e818_0    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cairo                     1.16.0            h0ab9d94_1001    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cfitsio                   3.430             h50cca31_1002    conda-forge
curl                      7.64.1               h22ea746_0    conda-forge
dcw-gmt                   1.1.4                      1001    conda-forge
expat                     2.2.5             h0a44026_1002    conda-forge
fftw                      3.3.8           nompi_h5c49c53_1105    conda-forge
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freetype                  2.10.0               h24853df_0    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
gdal                      2.4.1            py37h39889d8_4    conda-forge
geos                      3.7.1             h0a44026_1000    conda-forge
geotiff                   1.5.1                h83de174_2    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
ghostscript               9.22              h0a44026_1001    conda-forge
giflib                    5.1.7                h01d97ff_1    conda-forge
glib                      2.58.3            h9d45998_1001    conda-forge
gmt                       6.0.0rc1             hc6df392_0    conda-forge/label/dev
gshhg-gmt                 2.3.7                      1002    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.5          nompi_h0cbb7df_1100    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
kealib                    1.4.10            h6659575_1005    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libcurl                   7.64.1               h16faf7d_0    conda-forge
libcxx                    8.0.0                         2    conda-forge
libcxxabi                 8.0.0                         2    conda-forge
libdap4                   3.19.1            hae55d67_1000    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgdal                   2.4.1                hbed8f18_4    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libkml                    1.3.0             hed7d534_1010    conda-forge
liblapack                 3.8.0                7_openblas    conda-forge
libnetcdf                 4.6.2             h1a02027_1002    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libpq                     11.3                 h56406e1_0    conda-forge
libspatialite             4.3.0a            he900ada_1028    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            hd08fb8f_1003    conda-forge
libxml2                   2.9.9                hd80cff7_0    conda-forge
llvm-openmp               8.0.0                h770b8ee_0    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.16.4           py37h6b0580a_0    conda-forge
openblas                  0.3.5             h436c29b_1001    conda-forge
openjpeg                  2.3.1                hc1feee7_0    conda-forge
openssl                   1.1.1b               h01d97ff_2    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pip                       19.1.1                   py37_0    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
poppler                   0.67.0               hb974355_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.3                 hf10c77c_0    conda-forge
proj4                     6.1.0                h2cc77ee_2    conda-forge
python                    3.7.3                h0d93f26_0    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sqlite                    3.28.0               h9721f7c_0    conda-forge
tk                        8.6.9             h2573ce8_1002    conda-forge
tzcode                    2019a             h01d97ff_1002    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xerces-c                  3.2.2             h44e365a_1001    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
zstd                      1.4.0                ha9f0a20_0    conda-forge
```

**Comment by seisman** [comment]
gmt pscoast also works for me.

**Comment by leouieda** [comment]
Yep, just figured it out. I had `channel_priority_strict` in my setup and that broke things.

**Pull request merged**
