### PR TITLE
Bump GMT dev version from 6.3.0.dev+52c6629 to 6.4.0.dev0+2eecd33

### PR DESCRIPTION
**Pull request by weiji14**
This PR will update the following package:
- [`gmt`][1] from [`6.3.0.dev+52c6629`][2] to [`6.4.0.dev0+2eecd33`][3]
  - Full list of commits made since last release viewable at [compare view][4]

Notes for merging this PR:
1. Feel free to push to the bot's branch to update this PR if needed.
2. Checklist before merging this PR:
  - [ ] Dependencies have been updated if changed
  - [ ] Tests have passed

[1]: https://github.com/GenericMappingTools/gmt
[2]: https://github.com/GenericMappingTools/gmt/commit/52c6629ebdd8533309abd6f34bcb545d60f84153
[3]: https://github.com/GenericMappingTools/gmt/commit/2eecd33dd9ed9d36362a87ce5f8ac5fad6d84434
[4]: https://github.com/GenericMappingTools/gmt/compare/52c6629ebdd8533309abd6f34bcb545d60f84153...2eecd33dd9ed9d36362a87ce5f8ac5fad6d84434

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by weiji14** [comment]
@conda-forge-admin, please rerender

**Comment by weiji14** [comment]
@seisman, maybe easier if I cherry-pick https://github.com/conda-forge/gmt-feedstock/pull/189/commits/a19bdba93ac0578cdc0b6d68bfe5d34bbe51b27f directly into this branch? Or do you think it's better to have a dev version of GMT 6.4.0 built with GDAL3.3/GEOS3.10.0 still?

**Comment by seisman** [comment]
> @seisman, maybe easier if I cherry-pick [a19bdba](https://github.com/conda-forge/gmt-feedstock/commit/a19bdba93ac0578cdc0b6d68bfe5d34bbe51b27f) directly into this branch?

Sounds good to me.

**Comment by weiji14** [comment]
@conda-forge-admin, please rerender

**Review by seisman — APPROVED** [review]

**Pull request merged**
