### PR TITLE
Rebuild for gdal34 and geos3101 in the devel branch

### PR DESCRIPTION
**Pull request by seisman**
Same as https://github.com/conda-forge/gmt-feedstock/pull/184 but for the devel branch.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by seisman** [comment]
@conda-forge-admin, please rerender

**Comment by weiji14** [comment]
@seisman, do you think we should bump the devel version to GMT 6.4 first? If so, I can open a PR for that, and then have this PR be rebased on top (or just include the version bump directly).

**Comment by seisman** [comment]
> do you think we should bump the devel version to GMT 6.4 first? If so, I can open a PR for that, and then have this PR be rebased on top (or just include the version bump directly).

Yes, please open a separate PR bumping the devel version.

**Comment by seisman** [comment]
Closed by #190.

**Pull request closed without merging**
