### PR TITLE
Enable Windows builds

### PR DESCRIPTION
**Pull request by leouieda**
Trying to get a Windows build going again. Took some things from #49 and other packages using cmake ([libpng](https://github.com/conda-forge/libpng-feedstock/blob/master/recipe/bld.bat)).

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leouieda** [comment]
@ocefpaf sorry to bother but I think I'm doing something stupid here and I can't figure out what. The builds are complaining about the patch file. Would you mind taking a quick look?

**Comment by ocefpaf** [comment]
> @ocefpaf sorry to bother but I think I'm doing something stupid here and I can't figure out what. The builds are complaining about the patch file. Would you mind taking a quick look?

Looking into it... Hold on.

**Comment by ocefpaf** [comment]
@leouieda the code base changed and that patch no longer applies. (Check the lines where the patch should go and you'll see that the lines to be deleted are not there.)

I'm not familiar with the code to know if you still need to force remove the matlab part or if there is some sort of auto-detection in cmake now. Either way, let's try to remove the patch altogether and see how it goes.

**Comment by leouieda** [comment]
Thanks, Filipe! The patch is still needed because GMT still tries to build the Matlab interface on Windows. On the master branch it checks for a variable but not on 5.4.5. That was my mistake actually. I made the patch on master instead of 5.4.5. Will try again.

**Comment by leouieda** [comment]
OK, that worked. The problem now is finding GSHHG. In the tests, it seems to be looking for it in the build environment rather than the test environment.

**Comment by ocefpaf** [comment]
> OK, that worked. The problem now is finding GSHHG. In the tests, it seems to be looking for it in the build environment rather than the test environment.

Ah. The same old problem :-(

@isuruf and @mingwandroid you are the only ones that know Windows well enough to help us :smile: 

Do you have any advice for us here?

**Comment by seisman** [comment]
As I understand it, the conda-forge recipe first creates a build environment (`_h_env`) to build the codes and package it as a tarball. Then it creates another build environment (`_test_env`) to check if the the tarball works for users.

Here, the problem is, when building GMT, the GSHHG root is configured to be `D:\bld\gmt_1553105528302\_h_env\Library\share\gshhg-gmt`. However, the test environment `_test_env` cannot access the build environment `_h_env` (I guess the build environment has been delete?). 

GMT tries to search GSHHG files in following directories:
1. GSHHG ROOT path as configured when building, i.e. `D:/bld/gmt_1553105528302/_h_env/Library/share/gshhg-gmt`, which cannot be accessed.
2. search in directories listed in the file `share/conf/coastline.conf` or `share/coast/coastline.conf`. Both don't exist by default.
3. search in `share/coast`, which doesn't exists, because conda installed gshhg-gmt is located in `share/gshhg-gmt`.

**Comment by leouieda** [comment]
@joa-quim do you have any Windows insights on this? The main problem is that the coastline data path is not fixed but is relative to the library directory. This is a problem because we package the data separately.

**Comment by joa-quim** [comment]
This coastlines story is the main source of troubles for building GMT. Confess that I was never found on the decision to split it from the main source code. I had the same annoyances when creating the ``Vcpkg`` portfile. Maybe it helps to see what ended up doing:
```
vcpkg_download_distfile(ARCHIVE
    URLS "https://mirrors.ustc.edu.cn/gmt/gshhg-gmt-2.3.7.tar.gz"
    FILENAME "gshhg.tar.gz"
    SHA512 27e97efe9d146a58d1c6674c5b6cde6b7545be60c1f7d3d93faca1034986d1648e73b589de571897fc53cd0d050a5875dcc9923e3f861f8473ca568a8142d727
)
vcpkg_extract_source_archive(${ARCHIVE} ${SOURCE_PATH}/share)

vcpkg_download_distfile(ARCHIVE
    URLS "https://mirrors.ustc.edu.cn/gmt/dcw-gmt-1.1.4.tar.gz"
    FILENAME "dcw.tar.gz"
    SHA512 3ea64ce9cc162030b40da859e8617e6c724c3529a57d2e6ae8dc311b4397532d8946aac7f66f49707dc85d046e892faa77bf1293a66c949fdf0473028dc4beeb
)
vcpkg_extract_source_archive(${ARCHIVE} ${SOURCE_PATH}/share)
```
As you can see, I download from @seisman host and place the files under the GMT's ``share`` dir

**Comment by joa-quim** [comment]
> The patch is still needed because GMT still tries to build the Matlab interface on Windows.

Nope, not right. The build does not try to build the MEXs. That's a separate repo. Why do you think so?

**Comment by leouieda** [comment]
@joa-quim sorry that was a mistake. It's not trying to build the MEX package but these lines in the cmake are failing because it's looking for it:

```
if (WIN32 AND TRUE) 
		# Install the gmtmex on Windows. Need to make this work via variables in ConfigUser.cmake
		if (BITAGE EQUAL 64)
			install (PROGRAMS ${GMTMEX_PATH}/gmtmex.mexw64 DESTINATION ${GMT_BINDIR} COMPONENT Runtime)
		else ()
			install (PROGRAMS ${GMTMEX_PATH}/gmtmex.mexw32 DESTINATION ${GMT_BINDIR} COMPONENT Runtime)
		endif ()
		install (PROGRAMS ${GMTMEX_PATH}/../../src/gmt.m DESTINATION ${GMT_BINDIR} COMPONENT Runtime)
endif (WIN32 AND TRUE) 
```

https://github.com/GenericMappingTools/gmt/blob/5.4/cmake/dist/CMakeLists.txt#L171

**Comment by seisman** [comment]
> @joa-quim do you have any Windows insights on this? The main problem is that the coastline data path is not fixed but is relative to the library directory. This is a problem because we package the data separately.

@leouieda I'm curious why we don't have the problem for linux and osx?

**Comment by leouieda** [comment]
A miracle has happened today :pray:  I had to ask GMT to package the coastline data when building the package. This only happens on Windows. It's not the best way to do it because GMT will continue to use older data if the data packages are updated. But seeing as this pretty much never happens, it shouldn't be an issue. We can always make a new build if the data are updated.

**Comment by seisman** [comment]
For windows users, they will have two copies of gshhg data. One is bundled in the gmt package, another is automatically installed, as gshhg is a dependency of gmt.

**Comment by leouieda** [comment]
Yes, that's true. These are small datasets, though, so I don't think it's a huge problem. This is not ideal but it will do until we have a better fix. I'm not entirely sure it's useful to package the data separately from GMT in the first place since they don't really change much and nobody uses GMT without the data.

**Comment by leouieda** [comment]
>  they don't really change much 

Reading that I realize that it's the reason for packaging separately...

**Comment by leouieda** [comment]
@seisman could you give this a try if you have access to a Windows machine?

**Comment by seisman** [comment]
@leouieda I tried the built-in example 02 on Windows. Works well.

**Comment by leouieda** [comment]
Great! Thank :tada:

**Comment by seisman** [comment]
Found an issue with the Windows package, which may cause troubles.

On macOS, the GMT share files/directories are installed in `${MINICONDA}/Library/share/gmt`. However, on Windows, they are installed in `${MINICONDA}/Library/share/`. See the attached screenshot below. If there are any other packages which have share files with the same names (`custom`, `man`, `localization` et al. are common names), it would conflict. 
image

**Comment by leouieda** [comment]
Oh, that's interesting. So apparently GMT is not appending `gmt` to `%LIBRARY_PREFIX%` `CMAKE_INSTALL_DIR`? I'll try adding `gmt` to that and publishing another build.

**Comment by ocefpaf** [comment]
> Yes, that's true. These are small datasets, though, so I don't think it's a huge problem. This is not ideal but it will do until we have a better fix. I'm not entirely sure it's useful to package the data separately from GMT in the first place since they don't really change much and nobody uses GMT without the data.

@leouieda you can use a pre-processor selector to avoid installing the data on Windows twice. You will have to add `#  [not win]` in front of the dataset dependencies.

**Comment by leouieda** [comment]
>  You will have to add # [not win] in front of the dataset dependencies.

But we still need them at compile time. Should I add them as `built` dependencies with `# [win]`?

**Comment by ocefpaf** [comment]
> @ocefpaf but we still need them at compile time.

OK.

> Should I add them as built dependencies with # [win]?

If I understand this PR correct the build will copy it on Windows, right? If so you can "remove" it from `run` only on Windows (by adding the `#  [not win]` on the run-time only).

**Comment by leouieda** [comment]
Got it. OK, will test this out in #64

**Pull request merged**
