### PR TITLE
Rebuild for gdal34 and geos3101

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

We have a narrow dependency path here, see conda-forge/gdal-feedstock#585 , so lets try migrating geos and gdal at the same time.

### CODE REVIEW

**Comment by akrherz** [comment]
Hmmm, dependencies are resolved now, but cmake is failing :/

```
2021-12-04T21:00:44.0145866Z CMake version: 3.21.3
2021-12-04T21:00:44.0245534Z CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
2021-12-04T21:00:44.0246566Z CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
2021-12-04T21:00:44.0247553Z -- Configuring incomplete, errors occurred!
```

**Comment by akrherz** [comment]
If you want me to tighten up the git history, I certainly can, please let me know. Hopefully this is all green.

**Comment by akrherz** [comment]
I went ahead and cleaned it up, hopefully I did not jinx it :)

**Review by seisman — APPROVED** [review]

**Comment by seisman** [comment]
@akrherz great! Thanks!

**Pull request merged**
